Instructions to Configure iOS Project To Use Danger For Build Reporting
IntrepidPursuits/sherpa pull request #59
Opened 2016-11-30 18:37 UTC by djbrooks111

2016-11-30 19:31 UTC, brightredchilli commented on ios_danger.md
> +We have abandoned the Jenkins' Xcode Plugin because it is no longer being maintained and does not allow for the level of customization we desire. Please update your Jenkins project to match the `ios-
Have we really abandoned the xcode plugin? Are we not able to run scan as a post xcode plugin script?

2016-11-30 19:31 UTC, brightredchilli commented on ios_danger.md
> +## Existing Projects Using Scan Inside An 'Execute Shell' Phase
We should clarify what happens if you already have a Dangerfile in your project. What are the instructions?

2016-11-30 19:31 UTC, brightredchilli commented on ios_danger.md
> +Therefore, to ease our Pull Request process, we are integrating [Danger](http://danger.systems) into our Jenkins projects. More specifically, we are using this Danger plugin called [Danger Xcode Summ
Add link to the script that looks for existing Dangerfile as part of the build process, creating and adding it if necessary.

2016-11-30 19:31 UTC, brightredchilli commented on ios_danger.md
> +Please clone the `ios-pull-request-template` found [here](http://ci.intrepid.io:8080/view/Templates/job/ios-pull-request-template/) and make the changes stated in that project to work with your speci
Add links on how to disable this step if those are not too complicated.

2016-12-01 01:46 UTC, alexpersian commented on ios_danger.md
> +We have abandoned the Jenkins' Xcode Plugin because it is no longer being maintained and does not allow for the level of customization we desire. Please update your Jenkins project to match the `ios-
Xcode 8.0+ no longer supports plugins unless they are built through `SourceKit` AFAIK.

2016-12-01 15:24 UTC, djbrooks111 commented on ios_danger.md
> +## Existing Projects Using Scan Inside An 'Execute Shell' Phase
Done

2016-12-02 16:07 UTC, tzm41 approved these changes

2016-12-02 16:17 UTC, ButkiewiczP approved these changes

2016-12-06 17:46 UTC, brightredchilli requested changes

2016-12-06 17:46 UTC, brightredchilli commented on ios_danger.md
> +If for some reason there is an issue with danger and/or its integration, simply comment out the call to the danger script like so:
Please add this to a new top level category at the bottom, '## Troubleshooting issues with Danger'

2017-01-30 19:33 UTC, merged