Add instructions for setting up iOS project
IntrepidPursuits/sherpa pull request #67
Opened 2017-02-27 16:42 UTC by mayasaxena

Instructions for creating an iOS project from scratch. Includes instructions for:
- Github repo and Xcode project setup
- Cocoapods installation
- Jenkins job setup

2017-02-27 20:01 UTC, andrewdolce approved these changes
:shipit:

2017-02-27 20:35 UTC, djbrooks111 requested changes

2017-02-27 20:35 UTC, djbrooks111 commented on ios/ios_project_setup.md
> +    - For pull requests, add:
This should be handled automatically for you if you hit the "Manage hooks for you" within the Pull Request Builder plugin in your Jenkins project

2017-02-27 20:35 UTC, djbrooks111 commented on ios/ios_project_setup.md
> +    - Copy `ios-pull-request-template` on Jenkins and replace the variables as directed. Go to Build Triggers and click Advanced, then add "retest this please" as the "Trigger phrase" so that Jenkins
"retest this please" is already globally configured, you only need to edit this field if you want to change the phrase.

2017-02-27 20:35 UTC, djbrooks111 commented on ios/ios_project_setup.md
> +    - For pull requests, add:
These web hooks should be moved to a troubleshooting section

2017-02-27 20:35 UTC, alexpersian commented on ios/ios_project_setup.md
> +1. Add and commit, then push to `master`
Do we have any guidelines on initial branches to create? ex: adding a `develop` branch

2017-02-27 21:02 UTC, djbrooks111 approved these changes

2017-02-27 21:07 UTC, mayasaxena commented on ios/ios_project_setup.md
> +1. Add and commit, then push to `master`
I don't know if we have anything official - Andrew also mentioned adding sections on directory structure, Crashlytics setup, etc but maybe those could be added in via PR once we reach a consensus.

2017-02-27 21:21 UTC, bobgilmore approved these changes

2017-02-28 16:13 UTC, alexpersian commented on ios/ios_project_setup.md
> +1. Add and commit, then push to `master`
Based on the conversation in #dev today it seems like this is more of a project by project basis. Agreed on them being a future PR if needed.

2017-02-28 16:13 UTC, alexpersian approved these changes

2017-02-28 16:15 UTC, merged