Add recommended tools page
IntrepidPursuits/sherpa pull request #68
Opened 2017-02-27 20:00 UTC by MaxHasADHD

2017-02-27 20:44 UTC, alexpersian requested changes

2017-02-27 20:44 UTC, alexpersian commented on ios/ios_recommended_tools.md
> +[Useful collection of Xcode breakpoints](https://gist.github.com/gbernady/1fc53d70587b9064f84c)
Add information in "Processes" on Xcode user breakpoints and why we should use them

2017-02-28 16:17 UTC, alexpersian requested changes

2017-02-28 16:17 UTC, alexpersian commented on ios/ios_recommended_tools.md
> +Breakpoints are helpful for debugging code. Specifically if a line of code was called when you expect it to be called or not. Breakpoints can be added, moved, edited, and deleted while debugging and
My fault on not being specific before. This section explaining breakpoints themselves can be removed. I think most everyone knows what breakpoints are and how to generally use them.

I think the article from Natasha on _user breakpoints_ is useful to keep in though.

2017-03-08 19:28 UTC, alexpersian approved these changes

2017-03-17 17:53 UTC, Benuuu approved these changes

2017-05-12 18:33 UTC, merged