Initial draft of MVVM testing walkthrough
IntrepidPursuits/sherpa pull request #70
Opened 2017-03-07 13:29 UTC by weberbry

This post provide a basic walkthrough of my talk on testing approaches for MVVM apps.

2017-03-08 21:23 UTC, alexpersian requested changes
Also I'd recommend surrounding the class names throughout with backticks. ie: `ClassName`

2017-03-08 21:23 UTC, alexpersian commented on ios/MVVM_Testing.md
> +In terms of view models, the SearchViewController is backed by a SearchViewModel and each AlbumSearchResultTableViewCell is backed by a AlbumSearchResultCellViewModel.
"...backed by **an** Album..."

2017-03-08 21:23 UTC, alexpersian commented on ios/MVVM_Testing.md
> +The AlbumSearchResultCellViewModel is primarily a thin wrapper around the album model, providing some presentation logic. This type of presentation logic place to start when writing view model tests.
"This type of presentation..." sentence reads weirdly.

2017-03-08 21:23 UTC, alexpersian commented on ios/MVVM_Testing.md
> +```func testBasicAlbumSearch() {
Return after ```

2017-03-08 21:23 UTC, alexpersian commented on ios/MVVM_Testing.md
> +```func testAlbumViewModelAtIndex() {
Return after ```

2017-03-17 17:51 UTC, Benuuu approved these changes

2017-03-17 17:51 UTC, Benuuu commented on ios/MVVM_Testing.md
> +The entire app codebase for this test app can be found [here](https://github.com/weberbry/ViewModelTestingDemo).
I've created a repo for MVVM examples:

https://github.com/IntrepidPursuits/MVVMExamples-ios

Lets consolidate these?

2017-03-17 17:51 UTC, Benuuu commented on ios/MVVM_Testing.md
> +
Clean up some of this whitespace.  Also the indentation looks wrong for `self?.albumViewModels =...`

2017-03-17 17:51 UTC, Benuuu commented on ios/MVVM_Testing.md
> +    func setHasPreviouslyLoaded(hasPreviouslyLoaded: Bool) {
Where is this function used?  Can we remove it from the example here?

2017-03-21 18:25 UTC, weberbry commented on ios/MVVM_Testing.md
> +The entire app codebase for this test app can be found [here](https://github.com/weberbry/ViewModelTestingDemo).
Added PR for the MVVMExamples-ios codebase
https://github.com/IntrepidPursuits/MVVMExamples-ios/pull/2

2017-03-21 19:32 UTC, tzm41 commented on ios/MVVM_Testing.md
> +The view model often acts as the first layer of abstraction between the view and the business logic, networking and data layer of an app. That said, view model tests should not be responsible for tes
`method should not test the actual networking later`. Did you mean `layer`?

2017-03-24 20:31 UTC, alexpersian approved these changes

2017-03-24 20:31 UTC, merged